/**
 * Deploy Tools — 部署工具集 (v1.0)
 *
 * 为 Agent 提供自动化部署能力:
 *   1. Docker Compose — 编排多容器服务
 *   2. PM2 — Node.js 进程管理
 *   3. Nginx — 反向代理配置生成
 *   4. 端口检测 — 自动发现可用端口
 *   5. 健康检查 — 验证服务启动成功
 *
 * 设计原则:
 *   - 全部通过 Docker Sandbox 执行，不污染宿主机
 *   - 生成标准化配置文件，agent 可审查 / 编辑
 *   - 支持 one-click 部署到本地 Docker 环境
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs';
import path from 'path';
import { createLogger } from './logger';

const log = createLogger('deploy-tools');
const execAsync = promisify(exec);

// ═══════════════════════════════════════
// Types
// ═══════════════════════════════════════

export interface ServiceConfig {
  name: string;
  /** Docker 镜像 */
  image?: string;
  /** Dockerfile 路径 (image 和 build 二选一) */
  build?: string;
  /** 端口映射 host:container */
  ports: string[];
  /** 环境变量 */
  env?: Record<string, string>;
  /** 挂载卷 host:container */
  volumes?: string[];
  /** 依赖的其他服务 */
  dependsOn?: string[];
  /** 健康检查命令 */
  healthCheck?: string;
  /** 重启策略 */
  restart?: 'always' | 'unless-stopped' | 'on-failure' | 'no';
  /** 内存限制 */
  memoryLimit?: string;
  /** 自定义 command */
  command?: string;
}

export interface ComposeConfig {
  projectName: string;
  services: ServiceConfig[];
  /** 公共网络名 */
  networkName?: string;
}

export interface DeployResult {
  success: boolean;
  output: string;
  error?: string;
  /** 生成的配置文件路径列表 */
  generatedFiles: string[];
  /** 可访问的 URL 列表 */
  urls: string[];
}

export interface HealthCheckResult {
  success: boolean;
  /** 各服务状态 */
  services: Array<{
    name: string;
    healthy: boolean;
    url?: string;
    responseTime?: number;
    error?: string;
  }>;
}

export interface PM2AppConfig {
  name: string;
  script: string;
  cwd?: string;
  args?: string;
  instances?: number | 'max';
  env?: Record<string, string>;
  maxMemoryRestart?: string;
  logFile?: string;
  watch?: boolean;
}

// ═══════════════════════════════════════
// Docker Compose
// ═══════════════════════════════════════

/**
 * 生成 docker-compose.yml 内容
 */
export function generateComposeYaml(config: ComposeConfig): string {
  const lines: string[] = [];

  // docker compose 规范版本不再需要，用默认最新 compose spec
  lines.push(`# Auto-generated by AutoMater Deploy Tools`);
  lines.push(`# Project: ${config.projectName}`);
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('services:');

  for (const svc of config.services) {
    lines.push(`  ${svc.name}:`);

    if (svc.image) {
      lines.push(`    image: ${svc.image}`);
    }
    if (svc.build) {
      lines.push(`    build:`);
      lines.push(`      context: .`);
      lines.push(`      dockerfile: ${svc.build}`);
    }
    if (svc.command) {
      lines.push(`    command: ${svc.command}`);
    }
    if (svc.ports.length > 0) {
      lines.push(`    ports:`);
      for (const p of svc.ports) {
        lines.push(`      - "${p}"`);
      }
    }
    if (svc.env && Object.keys(svc.env).length > 0) {
      lines.push(`    environment:`);
      for (const [k, v] of Object.entries(svc.env)) {
        lines.push(`      ${k}: "${v}"`);
      }
    }
    if (svc.volumes && svc.volumes.length > 0) {
      lines.push(`    volumes:`);
      for (const v of svc.volumes) {
        lines.push(`      - ${v}`);
      }
    }
    if (svc.dependsOn && svc.dependsOn.length > 0) {
      lines.push(`    depends_on:`);
      for (const d of svc.dependsOn) {
        lines.push(`      - ${d}`);
      }
    }
    if (svc.healthCheck) {
      lines.push(`    healthcheck:`);
      lines.push(`      test: ${svc.healthCheck}`);
      lines.push(`      interval: 10s`);
      lines.push(`      timeout: 5s`);
      lines.push(`      retries: 3`);
    }
    if (svc.restart) {
      lines.push(`    restart: ${svc.restart}`);
    }
    if (svc.memoryLimit) {
      lines.push(`    deploy:`);
      lines.push(`      resources:`);
      lines.push(`        limits:`);
      lines.push(`          memory: ${svc.memoryLimit}`);
    }
    lines.push('');
  }

  if (config.networkName) {
    lines.push('networks:');
    lines.push(`  ${config.networkName}:`);
    lines.push(`    driver: bridge`);
  }

  return lines.join('\n');
}

/**
 * 将 compose 配置写入文件并执行 docker compose up
 */
export async function deployWithCompose(
  config: ComposeConfig,
  workspacePath: string,
  options?: { detach?: boolean; buildFirst?: boolean; timeout?: number },
): Promise<DeployResult> {
  const generatedFiles: string[] = [];
  const urls: string[] = [];

  try {
    // 1. 生成 docker-compose.yml
    const yaml = generateComposeYaml(config);
    const composePath = path.join(workspacePath, 'docker-compose.yml');
    fs.writeFileSync(composePath, yaml, 'utf-8');
    generatedFiles.push(composePath);
    log.info(`Generated docker-compose.yml at ${composePath}`);

    // 2. 执行 docker compose up
    const detachFlag = options?.detach !== false ? '-d' : '';
    const buildFlag = options?.buildFirst ? '--build' : '';
    const cmd = `docker compose -f "${composePath}" up ${detachFlag} ${buildFlag}`.trim();

    log.info(`Executing: ${cmd}`);
    const timeout = options?.timeout || 120_000;
    const { stdout, stderr } = await execAsync(cmd, { cwd: workspacePath, timeout });

    // 3. 收集 URLs
    for (const svc of config.services) {
      for (const portMap of svc.ports) {
        const hostPort = portMap.split(':')[0];
        urls.push(`http://localhost:${hostPort}`);
      }
    }

    return {
      success: true,
      output: `部署成功 ✅\n\n${stdout}\n${stderr ? `⚠️ ${stderr}` : ''}\n\n可访问 URL:\n${urls.map(u => `  → ${u}`).join('\n')}`,
      generatedFiles,
      urls,
    };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    log.error(`Compose deploy failed: ${msg}`);
    return { success: false, output: '', error: msg, generatedFiles, urls };
  }
}

/**
 * 停止并清理 compose 服务
 */
export async function composeDown(
  workspacePath: string,
): Promise<{ success: boolean; output: string; error?: string }> {
  try {
    const composePath = path.join(workspacePath, 'docker-compose.yml');
    if (!fs.existsSync(composePath)) {
      return { success: false, output: '', error: 'docker-compose.yml 不存在' };
    }
    const { stdout, stderr } = await execAsync(`docker compose -f "${composePath}" down -v`, {
      cwd: workspacePath,
      timeout: 60_000,
    });
    return { success: true, output: `服务已停止并清理\n${stdout}\n${stderr}` };
  } catch (err: unknown) {
    return { success: false, output: '', error: err instanceof Error ? err.message : String(err) };
  }
}

// ═══════════════════════════════════════
// PM2 Process Manager
// ═══════════════════════════════════════

/**
 * 生成 PM2 ecosystem 配置文件
 */
export function generatePM2Ecosystem(apps: PM2AppConfig[]): string {
  const ecosystem = {
    apps: apps.map(app => ({
      name: app.name,
      script: app.script,
      cwd: app.cwd || '.',
      args: app.args || '',
      instances: app.instances || 1,
      env: app.env || {},
      max_memory_restart: app.maxMemoryRestart || '500M',
      log_file: app.logFile || `./logs/${app.name}.log`,
      watch: app.watch || false,
      autorestart: true,
      merge_logs: true,
    })),
  };

  return `// PM2 Ecosystem — Auto-generated by AutoMater
module.exports = ${JSON.stringify(ecosystem, null, 2)};
`;
}

/**
 * 启动 PM2 进程
 */
export async function pm2Start(apps: PM2AppConfig[], workspacePath: string): Promise<DeployResult> {
  const generatedFiles: string[] = [];

  try {
    // 生成 ecosystem.config.js
    const content = generatePM2Ecosystem(apps);
    const configPath = path.join(workspacePath, 'ecosystem.config.js');
    fs.writeFileSync(configPath, content, 'utf-8');
    generatedFiles.push(configPath);

    // 确保 logs 目录存在
    const logsDir = path.join(workspacePath, 'logs');
    fs.mkdirSync(logsDir, { recursive: true });

    // 启动
    const { stdout, stderr } = await execAsync(`npx pm2 start ecosystem.config.js`, {
      cwd: workspacePath,
      timeout: 30_000,
    });

    return {
      success: true,
      output: `PM2 启动成功 ✅\n${stdout}\n${stderr || ''}`,
      generatedFiles,
      urls: [],
    };
  } catch (err: unknown) {
    return {
      success: false,
      output: '',
      error: err instanceof Error ? err.message : String(err),
      generatedFiles,
      urls: [],
    };
  }
}

/**
 * PM2 状态查询
 */
export async function pm2Status(): Promise<{ success: boolean; output: string }> {
  try {
    const { stdout } = await execAsync('npx pm2 jlist', { timeout: 10_000 });
    const processes = JSON.parse(stdout) as Array<{
      name: string;
      pm2_env: { status: string; pm_uptime: number; restart_time: number };
      monit: { cpu: number; memory: number };
    }>;

    if (processes.length === 0) return { success: true, output: '无 PM2 进程运行' };

    const lines = processes.map(p => {
      const uptime = Math.round((Date.now() - p.pm2_env.pm_uptime) / 1000);
      const mem = Math.round(p.monit.memory / 1024 / 1024);
      return `${p.name}: ${p.pm2_env.status} | uptime=${uptime}s | cpu=${p.monit.cpu}% | mem=${mem}MB | restarts=${p.pm2_env.restart_time}`;
    });

    return { success: true, output: lines.join('\n') };
  } catch (err: unknown) {
    return { success: false, output: err instanceof Error ? err.message : String(err) };
  }
}

// ═══════════════════════════════════════
// Nginx Config Generator
// ═══════════════════════════════════════

export interface NginxSiteConfig {
  serverName: string;
  listenPort?: number;
  /** 后端服务地址 */
  upstream: string;
  /** 静态文件根目录 */
  staticRoot?: string;
  /** 启用 SSL (需提供 cert/key 路径) */
  ssl?: {
    certPath: string;
    keyPath: string;
  };
  /** SPA 模式 — 所有路由 fallback 到 index.html */
  spaMode?: boolean;
  /** 额外 location 块 */
  extraLocations?: Array<{
    path: string;
    proxyPass?: string;
    root?: string;
    tryFiles?: string;
  }>;
}

/**
 * 生成 Nginx 站点配置
 */
export function generateNginxConfig(config: NginxSiteConfig): string {
  const lines: string[] = [];
  const port = config.listenPort || (config.ssl ? 443 : 80);

  lines.push(`# Nginx config — Auto-generated by AutoMater`);
  lines.push(`# Server: ${config.serverName}`);
  lines.push('');
  lines.push(`upstream backend_${config.serverName.replace(/\./g, '_')} {`);
  lines.push(`    server ${config.upstream};`);
  lines.push('}');
  lines.push('');
  lines.push('server {');
  lines.push(`    listen ${port}${config.ssl ? ' ssl http2' : ''};`);
  lines.push(`    server_name ${config.serverName};`);
  lines.push('');

  if (config.ssl) {
    lines.push(`    ssl_certificate     ${config.ssl.certPath};`);
    lines.push(`    ssl_certificate_key ${config.ssl.keyPath};`);
    lines.push(`    ssl_protocols       TLSv1.2 TLSv1.3;`);
    lines.push(`    ssl_ciphers         HIGH:!aNULL:!MD5;`);
    lines.push('');
  }

  // Gzip
  lines.push('    gzip on;');
  lines.push('    gzip_types text/plain text/css application/json application/javascript text/xml;');
  lines.push('    gzip_min_length 1024;');
  lines.push('');

  // 静态文件
  if (config.staticRoot) {
    lines.push(`    root ${config.staticRoot};`);
    lines.push('');
    lines.push('    location /assets/ {');
    lines.push('        expires 30d;');
    lines.push('        add_header Cache-Control "public, immutable";');
    lines.push('    }');
    lines.push('');
  }

  // API 反向代理
  lines.push('    location /api/ {');
  lines.push(`        proxy_pass http://backend_${config.serverName.replace(/\./g, '_')};`);
  lines.push('        proxy_http_version 1.1;');
  lines.push('        proxy_set_header Upgrade $http_upgrade;');
  lines.push('        proxy_set_header Connection "upgrade";');
  lines.push('        proxy_set_header Host $host;');
  lines.push('        proxy_set_header X-Real-IP $remote_addr;');
  lines.push('        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;');
  lines.push('        proxy_set_header X-Forwarded-Proto $scheme;');
  lines.push('        proxy_read_timeout 300s;');
  lines.push('    }');
  lines.push('');

  // 额外 location 块
  if (config.extraLocations) {
    for (const loc of config.extraLocations) {
      lines.push(`    location ${loc.path} {`);
      if (loc.proxyPass) lines.push(`        proxy_pass ${loc.proxyPass};`);
      if (loc.root) lines.push(`        root ${loc.root};`);
      if (loc.tryFiles) lines.push(`        try_files ${loc.tryFiles};`);
      lines.push('    }');
      lines.push('');
    }
  }

  // SPA fallback
  if (config.spaMode) {
    lines.push('    location / {');
    lines.push('        try_files $uri $uri/ /index.html;');
    lines.push('    }');
  } else if (!config.staticRoot) {
    // 纯反向代理模式
    lines.push('    location / {');
    lines.push(`        proxy_pass http://backend_${config.serverName.replace(/\./g, '_')};`);
    lines.push('    }');
  }

  lines.push('}');
  return lines.join('\n');
}

/**
 * 写入 nginx 配置到指定路径
 */
export async function writeNginxConfig(
  config: NginxSiteConfig,
  outputDir: string,
): Promise<{ success: boolean; filePath: string; error?: string }> {
  try {
    fs.mkdirSync(outputDir, { recursive: true });
    const filePath = path.join(outputDir, `${config.serverName}.conf`);
    const content = generateNginxConfig(config);
    fs.writeFileSync(filePath, content, 'utf-8');
    log.info(`Nginx config written: ${filePath}`);
    return { success: true, filePath };
  } catch (err: unknown) {
    return { success: false, filePath: '', error: err instanceof Error ? err.message : String(err) };
  }
}

// ═══════════════════════════════════════
// Port & Health Check
// ═══════════════════════════════════════

/**
 * 检测端口是否可用
 */
export async function findAvailablePort(startPort: number = 3000, endPort: number = 9999): Promise<number> {
  // 使用 net 模块测试端口
  const net = await import('net');

  for (let port = startPort; port <= endPort; port++) {
    const available = await new Promise<boolean>(resolve => {
      const server = net.createServer();
      server.listen(port, '127.0.0.1');
      server.on('listening', () => {
        server.close();
        resolve(true);
      });
      server.on('error', () => resolve(false));
    });
    if (available) return port;
  }
  throw new Error(`无可用端口 (${startPort}-${endPort})`);
}

/**
 * 健康检查 — 轮询 URL 直到可达或超时
 */
export async function healthCheck(
  urls: Array<{ name: string; url: string; expectedStatus?: number }>,
  options?: { timeout?: number; interval?: number },
): Promise<HealthCheckResult> {
  const timeout = options?.timeout || 60_000;
  const interval = options?.interval || 2_000;
  const deadline = Date.now() + timeout;

  const results: HealthCheckResult['services'] = [];

  for (const target of urls) {
    const expected = target.expectedStatus || 200;
    let healthy = false;
    let responseTime = 0;
    let lastError = '';

    while (Date.now() < deadline) {
      const start = Date.now();
      try {
        const res = await fetch(target.url, {
          signal: AbortSignal.timeout(5_000),
        });
        responseTime = Date.now() - start;

        if (res.status === expected) {
          healthy = true;
          break;
        }
        lastError = `HTTP ${res.status} (expected ${expected})`;
      } catch (err: unknown) {
        lastError = err instanceof Error ? err.message : String(err);
        responseTime = Date.now() - start;
      }

      await new Promise(r => setTimeout(r, interval));
    }

    results.push({
      name: target.name,
      healthy,
      url: target.url,
      responseTime,
      error: healthy ? undefined : lastError,
    });
  }

  return {
    success: results.every(r => r.healthy),
    services: results,
  };
}

// ═══════════════════════════════════════
// Dockerfile Generator
// ═══════════════════════════════════════

export interface DockerfileConfig {
  /** 基础镜像 */
  baseImage: string;
  /** 工作目录 */
  workDir?: string;
  /** 安装依赖命令 */
  installCmd?: string;
  /** 构建命令 */
  buildCmd?: string;
  /** 暴露端口 */
  exposePorts?: number[];
  /** 启动命令 */
  startCmd: string;
  /** 复制文件 */
  copyFiles?: Array<{ src: string; dest: string }>;
  /** 多阶段构建: builder 阶段 */
  multiStage?: {
    builderImage: string;
    builderSteps: string[];
    copyFromBuilder: Array<{ src: string; dest: string }>;
  };
}

/**
 * 生成 Dockerfile
 */
export function generateDockerfile(config: DockerfileConfig): string {
  const lines: string[] = [];

  lines.push('# Dockerfile — Auto-generated by AutoMater');
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push('');

  if (config.multiStage) {
    // Multi-stage build
    lines.push(`FROM ${config.multiStage.builderImage} AS builder`);
    lines.push(`WORKDIR ${config.workDir || '/app'}`);
    for (const step of config.multiStage.builderSteps) {
      lines.push(step);
    }
    lines.push('');
    lines.push(`FROM ${config.baseImage}`);
    lines.push(`WORKDIR ${config.workDir || '/app'}`);
    for (const copy of config.multiStage.copyFromBuilder) {
      lines.push(`COPY --from=builder ${copy.src} ${copy.dest}`);
    }
  } else {
    lines.push(`FROM ${config.baseImage}`);
    lines.push(`WORKDIR ${config.workDir || '/app'}`);
  }

  // Copy files
  if (config.copyFiles) {
    for (const f of config.copyFiles) {
      lines.push(`COPY ${f.src} ${f.dest}`);
    }
  } else {
    lines.push('COPY . .');
  }

  // Install
  if (config.installCmd) {
    lines.push(`RUN ${config.installCmd}`);
  }

  // Build
  if (config.buildCmd) {
    lines.push(`RUN ${config.buildCmd}`);
  }

  // Expose
  if (config.exposePorts) {
    for (const p of config.exposePorts) {
      lines.push(`EXPOSE ${p}`);
    }
  }

  lines.push('');
  lines.push(`CMD ${config.startCmd}`);

  return lines.join('\n');
}

/**
 * 写入 Dockerfile
 */
export async function writeDockerfile(
  config: DockerfileConfig,
  outputPath: string,
): Promise<{ success: boolean; filePath: string; error?: string }> {
  try {
    const dir = path.dirname(outputPath);
    fs.mkdirSync(dir, { recursive: true });
    const content = generateDockerfile(config);
    fs.writeFileSync(outputPath, content, 'utf-8');
    log.info(`Dockerfile written: ${outputPath}`);
    return { success: true, filePath: outputPath };
  } catch (err: unknown) {
    return { success: false, filePath: '', error: err instanceof Error ? err.message : String(err) };
  }
}
