/**
 * Workspace Git — 项目工作区 Git 管理
 * 
 * - 项目创建时 git init + .gitignore
 * - 每个 phase 结束时自动 commit
 * - 项目导出为 zip
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

/**
 * 检测系统是否有 git
 */
export function hasGit(): boolean {
  try {
    execSync('git --version', { stdio: 'ignore' });
    return true;
  } catch { return false; }
}

/**
 * 在工作区初始化 git (如果还没有的话)
 */
export function initGitRepo(workspacePath: string): boolean {
  if (!hasGit()) return false;
  try {
    const gitDir = path.join(workspacePath, '.git');
    if (fs.existsSync(gitDir)) return true; // 已初始化

    execSync('git init', { cwd: workspacePath, stdio: 'ignore' });

    // 写 .gitignore
    const gitignore = `# Generated by AgentForge
node_modules/
dist/
build/
.env
.env.local
*.pyc
__pycache__/
.DS_Store
Thumbs.db
*.log
.vscode/
.idea/
`;
    fs.writeFileSync(path.join(workspacePath, '.gitignore'), gitignore, 'utf-8');

    // 配置 git user（避免 commit 时报错）
    try {
      execSync('git config user.email "agent@agentforge.dev"', { cwd: workspacePath, stdio: 'ignore' });
      execSync('git config user.name "AgentForge"', { cwd: workspacePath, stdio: 'ignore' });
    } catch { /* 非致命 */ }

    // 初始 commit
    execSync('git add -A', { cwd: workspacePath, stdio: 'ignore' });
    execSync('git commit -m "Initial commit by AgentForge" --allow-empty', { cwd: workspacePath, stdio: 'ignore' });

    return true;
  } catch (err) {
    console.error('[Git] Init failed:', err);
    return false;
  }
}

/**
 * 在工作区做一次 git commit
 */
export function commitWorkspace(workspacePath: string, message: string): boolean {
  if (!hasGit() || !fs.existsSync(path.join(workspacePath, '.git'))) return false;
  try {
    execSync('git add -A', { cwd: workspacePath, stdio: 'ignore' });
    // 检查是否有变更
    try {
      execSync('git diff --cached --quiet', { cwd: workspacePath, stdio: 'ignore' });
      return false; // 没有变更
    } catch {
      // diff --quiet 返回非零说明有变更，继续 commit
    }
    execSync(`git commit -m "${message.replace(/"/g, '\\"')}"`, { cwd: workspacePath, stdio: 'ignore' });
    return true;
  } catch (err) {
    console.error('[Git] Commit failed:', err);
    return false;
  }
}

/**
 * 获取 git log（简短）
 */
export function getGitLog(workspacePath: string, maxCount: number = 20): string[] {
  if (!hasGit() || !fs.existsSync(path.join(workspacePath, '.git'))) return [];
  try {
    const output = execSync(`git log --oneline -${maxCount}`, { cwd: workspacePath, encoding: 'utf-8' });
    return output.trim().split('\n').filter(Boolean);
  } catch { return []; }
}

/**
 * 将工作区打包为 zip (使用 Node 原生方式)
 */
export async function exportWorkspaceZip(workspacePath: string, outputPath: string): Promise<boolean> {
  // 用 archiver 太重，改用 PowerShell 打包（Windows 专用但够用）
  try {
    // 先确保目标路径不存在（Compress-Archive 不会覆盖）
    if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath);

    const cmd = `powershell -NoProfile -Command "Compress-Archive -Path '${workspacePath}\\*' -DestinationPath '${outputPath}' -Force"`;
    execSync(cmd, { stdio: 'ignore', timeout: 60000 });
    return fs.existsSync(outputPath);
  } catch (err) {
    console.error('[Export] Zip failed:', err);
    return false;
  }
}
